# -*- coding: utf-8 -*-
"""Introdução a data science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-SHqKhnCUW2Svwp5dzLgDGDyQYltcOJ
"""

import pandas as pd

notas = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/ml-latest-small/ratings.csv")
notas

notas.shape

notas.columns

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

notas["nota"]

notas["nota"].unique()

notas["nota"].value_counts()

notas["nota"].mean()

pd.read_csv('/content/ratings.csv')

notas["nota"].plot(kind='hist')

notas["nota"].median()

mediana = notas["nota"].median()
media = notas["nota"].mean()
print(f"Mediana é:{mediana}")
print(f"Media é: {media}")

notas["nota"].describe()

import seaborn as sns
sns.boxplot(notas["nota"])

# Criando um dataFrame simples
dados = {'Nome': ['Maria','Ana', 'Daniel'],
          'Idade': [25,30,35],
            'Salario': [5000,6000, 8000]}
df= pd.DataFrame(dados)
df

df.info()

df['Salario'].mean()
# ou df.Salario.mean()

import pandas as pd

# Criando um Series simples
idades = pd.Series([45, 30, 45, 40, 25])
idades

idades.index

idades.sort_values()